name: Publish Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: .
          version: latest

  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: make tests
  smoke_test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: actions/checkout@v4
      - run: |
          make compose-up
          sleep 3 # wait for the server to start
          curl -o /dev/null -s --retry 0 --head http://localhost:9999/warmup || exit 1
          echo "https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}" >> "${GITHUB_STEP_SUMMARY}"
  build-image:
    name: Build and Publish image
    runs-on: ubuntu-latest
    needs:
      - lint
      - acceptance-tests
      - smoke_test
    env:
      tag: stable
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: ./scripts/build-image.sh
